[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[window]
dimensions = { columns = 110, lines = 25 }
decorations = "Transparent"
dynamic_title = true
dynamic_padding = true
padding = { x = 12, y = 35 }
opacity = 1.0
blur = true

[font]
size = 16.0

[font.normal]
family = "0xProto Nerd Font"

[font.offset]
y = 2

[colors.primary]
background = "#101424"
foreground = "#bec6f2"

[colors.cursor]
cursor = "#bec6f2"
text = "#101424"

[colors.selection]
background = "#2d3b63"
text = "#ffffff"

[colors.normal]
black = "#0d1020"
red = "#ff9499"
green = "#c1f0cc"
yellow = "#f0e4c1"
blue = "#7bb1e0"
magenta = "#dda2d8"
cyan = "#5dc9dc"
white = "#bec6f2"

[colors.bright]
black = "#8f98c2"
red = "#ffb0bd"
green = "#d5f5dc"
yellow = "#fff0c8"
blue = "#93ddfb"
magenta = "#dda2f6"
cyan = "#89ddff"
white = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "On" }

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true }
binding = { key = "U", mods = "Control|Shift" }

[keyboard]
bindings = [
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "Q", mods = "Command", action = "Quit" },
]
