font_family 0xProto Nerd Font
font_size 16.0

background #111416
foreground #dddddd
cursor #dddddd
cursor_text_color #000000
selection_background #2466a9
selection_foreground #dddddd

color0 #111416
color1 #f14c4c
color2 #4ab386
color3 #cca700
color4 #3794ff
color5 #c586c0
color6 #4ec9b0
color7 #dddddd
color8 #808080
color9 #f44747
color10 #b5cea8
color11 #dcdcaa
color12 #4fc1ff
color13 #d7a9d2
color14 #9cdcfe
color15 #ffffff

background_opacity 1.0
window_padding_width 12
macos_option_as_alt yes
copy_on_select clipboard

enabled_layouts splits

map ctrl+shift+enter launch --cwd=current
map ctrl+shift+backspace close_window
map ctrl+shift+f toggle_layout stack

map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right

map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter

map ctrl+shift+t new_tab
map ctrl+shift+n next_tab
map ctrl+shift+p previous_tab
map ctrl+shift+w close_tab
